name: TruffleHog Secret Scan

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main, '**' ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog on PR diff
        uses: trufflesecurity/trufflehog@v3.76.0
        with:
          path: .
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.sha }}