name: Gitleaks Secrets Scan

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - release/*

jobs:
  gitleaks:
    name: Run Gitleaks Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks with License Key
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
          config-path: .github/gitleaks.toml
        env:
          GITLEAKS_LICENSE_KEY: E86E8A-22C271-B767AA-6055AC-F09CA3-V3