name: Gitleaks Secrets Scan

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - release/*

jobs:
  gitleaks:
    name: Run Gitleaks Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          args: >
            detect
            --source .
            --exit-code 1
            --report-path gitleaks-report.json