name: Gitleaks Secrets Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gitleaks:
    name: Scan for Secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true  # Fail the build if secrets are found