name: TruffleHog Full Scan

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main, '**' ]

jobs:
  trufflehog:
    name: Scan repo for secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: |
          curl -sSL https://github.com/trufflesecurity/trufflehog/releases/download/v3.89.1/trufflehog-linux-amd64 -o trufflehog
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/

      - name: Run TruffleHog scan
        run: trufflehog filesystem --directory . --only-verified